<?php

namespace mientras\Core\Proxies\__CG__\Mientras\Core\model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pedido extends \Mientras\Core\model\Pedido implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'fechaHora', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'proveedor', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'monto', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'montoDebe', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'estado', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'observaciones', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'user', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'detalles', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'fechaHoraRecibido', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'userRecibio'];
        }

        return ['__isInitialized__', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'fechaHora', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'proveedor', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'monto', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'montoDebe', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'estado', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'observaciones', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'user', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'detalles', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'fechaHoraRecibido', '' . "\0" . 'Mientras\\Core\\model\\Pedido' . "\0" . 'userRecibio'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pedido $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaHora', []);

        return parent::getFechaHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaHora($fechaHora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaHora', [$fechaHora]);

        return parent::setFechaHora($fechaHora);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontoDebe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontoDebe', []);

        return parent::getMontoDebe();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontoDebe($montoDebe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontoDebe', [$montoDebe]);

        return parent::setMontoDebe($montoDebe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalle(\Mientras\Core\model\DetallePedido $detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalle', [$detalle]);

        return parent::addDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalles', []);

        return parent::getDetalles();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalles($detalles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalles', [$detalles]);

        return parent::setDetalles($detalles);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedor($proveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedor', [$proveedor]);

        return parent::setProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRecibio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRecibio', []);

        return parent::getUserRecibio();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserRecibio($userRecibio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserRecibio', [$userRecibio]);

        return parent::setUserRecibio($userRecibio);
    }

    /**
     * {@inheritDoc}
     */
    public function podesAnularte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'podesAnularte', []);

        return parent::podesAnularte();
    }

    /**
     * {@inheritDoc}
     */
    public function podesPagarte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'podesPagarte', []);

        return parent::podesPagarte();
    }

    /**
     * {@inheritDoc}
     */
    public function podesRecibirte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'podesRecibirte', []);

        return parent::podesRecibirte();
    }

    /**
     * {@inheritDoc}
     */
    public function podesAnularRecepcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'podesAnularRecepcion', []);

        return parent::podesAnularRecepcion();
    }

    /**
     * {@inheritDoc}
     */
    public function isRecibido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRecibido', []);

        return parent::isRecibido();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaHoraRecibido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaHoraRecibido', []);

        return parent::getFechaHoraRecibido();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaHoraRecibido($fechaHoraRecibido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaHoraRecibido', [$fechaHoraRecibido]);

        return parent::setFechaHoraRecibido($fechaHoraRecibido);
    }

    /**
     * {@inheritDoc}
     */
    public function getOid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOid', []);

        return parent::getOid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOid', [$oid]);

        return parent::setOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncrypted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncrypted', []);

        return parent::getEncrypted();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncrypted($encrypted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncrypted', [$encrypted]);

        return parent::setEncrypted($encrypted);
    }

    /**
     * {@inheritDoc}
     */
    public function encrypt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encrypt', []);

        return parent::encrypt();
    }

    /**
     * {@inheritDoc}
     */
    public function decrypt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decrypt', []);

        return parent::decrypt();
    }

    /**
     * {@inheritDoc}
     */
    public function getManagedEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManagedEntities', []);

        return parent::getManagedEntities();
    }

}
